Firefox 105.0.3
pop-os/packaging-firefox pull request #25
Opened 2022-10-07 22:16 UTC by jacobgkau

https://www.mozilla.org/en-US/firefox/105.0.3/releasenotes/

Not sure if we actually need this, as the release notes indicate the only change was made for Windows.

2022-10-07 22:49 UTC, n3m0-22 submitted a review, later dismissed
Looks good.

[firefox-105.0.3-testing.txt](https://github.com/pop-os/packaging-firefox/files/9737777/firefox-105.0.3-testing.txt)

2022-10-07 22:52 UTC, 13r0ck requested changes
This should also update the debian changelog

2022-10-08 08:37 UTC, 13r0ck approved these changes
Thanks!

2022-10-08 14:04 UTC, n3m0-22 approved these changes

2022-10-10 14:24 UTC, merged